# Configuración avanzada de rustfmt (requiere nightly)
# Para usar: cargo +nightly fmt

# Habilitar características experimentales
unstable_features = true

# Estilo general
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports avanzados
imports_granularity = "Module"
reorder_imports = true
group_imports = "StdExternalCrate"

# Funciones y estructuras
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"
where_single_line = true

# Comentarios y documentación
comment_width = 80
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

# Formateo de código avanzado
use_small_heuristics = "Default"
newline_style = "Unix"
remove_nested_parens = true
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Arrays y estructuras
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false
struct_lit_single_line = true
fn_single_line = false

# Cadenas y literales
format_strings = false
format_macro_matchers = true
hex_literal_case = "Preserve"

# Características experimentales adicionales
wrap_method_calls = true
short_array_element_width_threshold = 10
condense_wildcard_suffixes = true
